services:
  - type: web
    name: voting-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn voting_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: voting-db
          property: connectionString

databases:
  - name: voting-db
    databaseName: voting_system
    user: voting_user
